version: '3.9'

services:
  employee-wishlist-nginx:
    image: 'nginx:stable-alpine'
    container_name: employee-wishlist-nginx
    ports:
      - "8001:80"
    volumes:
      - ./docker-configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
  employee-wishlist-api:
    build:
      context: .
      dockerfile: local.Dockerfile
    container_name: employee-wishlist-api
    image: employee-wishlist-api:latest
    volumes:
      - ./:/home/node
    # command: tail -F anything // Keep running container
    command: /home/node/node_modules/.bin/nodemon app.js
    depends_on:
      - employee-wishlist-mongo-db
  employee-wishlist-mongo-db:
    image: mongo:5.0
    container_name: employee-wishlist-mongo-db
    env_file:
      - ./docker-configs/env/mongo-db.env
    volumes:
      - employee_wishlist_mongo_data:/data/db
  employee-wishlist-mongo-express:
    image: mongo-express:latest
    container_name: employee-wishlist-mongo-express
    ports:
      - 8002:8081
    env_file:
      - ./docker-configs/env/mongo-express.env
    depends_on:
      - employee-wishlist-mongo-db
volumes: 
  employee_wishlist_mongo_data:
